apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
  namespace: default
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsName:
  - "solicitari.rednord.org"
  - "www.solicitari.rednord.org"
