apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-sercret
  namespace: default
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "solicitari.rednord.org"
  - "www.solicitari.rednord.org"
