# Generated by Django 4.0.6 on 2022-12-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.TextField(),
        ),
    ]
