# Generated by Django 4.0.6 on 2023-06-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.JSONField(),
        ),
    ]
