# A Temporary Pod to accomplish certain tasks with
# `postgres-pvc`

apiVersion: v1
kind: Pod
metadata:
  name: temp-postgres-pvc
spec:
  volumes:
    - name: postgres-volume
      persistentVolumeClaim:
        claimName: postgres-pvc
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - "sleep"
        - "infinity"
      volumeMounts:
        - mountPath: "/mnt"
          name: postgres-volume
