# Generated by Django 4.0.6 on 2022-12-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=255)),
                ('today', models.CharField(max_length=64)),
                ('sector', models.CharField(max_length=32)),
                ('pt', models.CharField(max_length=64)),
                ('feader', models.CharField(max_length=32)),
                ('account', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NORMAL', 'NORMAL'), ('URGENT', 'URGENT')], default='NORMAL', max_length=32)),
                ('remark', models.TextField(blank=True)),
                ('state', models.CharField(default='Neexecutat', max_length=64)),
            ],
        ),
    ]
