# Generated by Django 4.0.6 on 2023-01-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_app', '0002_call_email_ex_call_email_reg_call_name_ex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='today',
            new_name='date_reg',
        ),
        migrations.AddField(
            model_name='call',
            name='date_ex',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='call',
            name='email_ex',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='call',
            name='name_ex',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
