FROM nginx:1.23-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.k8s.conf /etc/nginx/conf.d

RUN mv /etc/nginx/conf.d/nginx.k8s.conf /etc/nginx/conf.d/nginx.conf

RUN mkdir -p /var/www/html/build/
RUN mkdir /var/www/html/static/
RUN mkdir /var/www/html/media/
