# Generated by Django 4.0.6 on 2023-06-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionobject',
            name='user',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
