apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
specs:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: solicitari-api:01
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
          name: api-config