apiVersion: apps/v1
king: Deployment
metadata:
  name: daphne-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: daphne
  template:
    metadata:
      labels:
        app: daphne
    spec:
      containers:
      - name: daphne
        image: solicitari-daphne:1.0
        ports:
        - containerPort: 8001
        command: ["daphne"]
        args: ["-b", "0.0.0.0", "-p", "8001", "sol_proj.asgi:application"]
        envFrom:
        - secretRef:
            name: daphne-secret
  
