apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: solicitari-nginx:1.0
        ports:
        - containerPort: 80
        # - containerPort: 443
        volumeMounts:
        - name: react-build
          mountPath: /var/www/html/build/
        - name: backend-static
          mountPath: /var/www/html/static/
        - name: backend-media
          mountPath: /var/www/html/media/
      volumes:
      - name: react-build
        persistentVolumeClaim:
          claimName: react-build-pvc
      - name: backend-static
        persistentVolumeClaim:
          claimName: backend-static-pvc
      - name: backend-media
        persistentVolumeClaim:
          claimName: backend-media-pvc
