apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: solicitari-web:1.0
        volumeMounts:
        - name: react-build-volume
          mountPath: /home/frontend
        envFrom:
        - configMapRef:
            name: web-config
      volumes:
      - name: react-build-volume
        persistentVolumeClaim:
          claimName: react-build-pvc

